#!/usr/bin/env bash
# Double the number of webservers

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sed -i '/listen 80 default_server/a add-header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sh -c 'echo "Hello World! This is my first web-server!" > /var/www/html/index.html'
sudo touch /var/www/html/404.html
sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'
service nginx restart
