#!/usr/bin/env bash
# Using while loop for Best Schools
# 4 is bad but 8 is good

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
