#!/usr/bin/env bash
# Changing my IP
cp /etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/hosts.new /etc/hosts
sed 's/127.0.0.1/127.0.0.2' /etc/hosts.new
echo "8.8.8.8.\tfacebook.com" >> /etc/hosts.new
