#!/usr/bin/env bash
# fixing a query issue

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo 'Hello Holberon' > sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
