#!/usr/bin/env bash
# Run Nginx as Nginx made shorter
sudo sed -i 's/user www-data/user nginx' /etc/nginc/nginx/conig
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx/conf
pkill apache2
sudo -u nginx service nginx restart
